apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: test
  name: test
spec:
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 80
  selector:
    app: test
  type: NodePort
status:
  loadBalancer: {}
